=== agovorov/epam-lab-3/src/main/resources/xml/planes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="planes" type="planesType">
        <xs:annotation>
            <xs:documentation>Список самолетов</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="planesType">
        <xs:sequence>
            <xs:element type="planeType" name="plane" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="charsType">
        <xs:sequence>

            <xs:element name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="самолет поддержки"/>
                        <xs:enumeration value="сопровождения"/>
                        <xs:enumeration value="истребитель"/>
                        <xs:enumeration value="перехватчик"/>
                        <xs:enumeration value="разведчик"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="seats" type="xs:integer" maxOccurs="2"/>
            <xs:element name="weapons" type="xs:boolean"/>
            <xs:element name="missiles" type="xs:decimal" maxOccurs="10"/>
            <xs:element name="hasRadar" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="priceType">
        <xs:sequence>
            <xs:element name="amount" type="xs:decimal"/>
            <xs:element name="currency" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parametersType">
        <xs:sequence>
            <xs:element name="length" type="xs:decimal"/>
            <xs:element name="width" type="xs:decimal"/>
            <xs:element name="height" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="planeType">
        <xs:sequence>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="origin" type="xs:string"/>

            <xs:element type="charsType" name="chars"/>
            <xs:element type="parametersType" name="parameters"/>
            <xs:element type="priceType" name="price"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== agovorov/epam-lab-3/src/main/resources/xml/planes.xml
<?xml version="1.0" encoding="UTF-8"?>
<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="planes.xsd">
    <plane>
        <model>Су-7</model>
        <origin>СССР</origin>
        <characteristics>
            <type>истребитель</type>
            <seats>1</seats>
            <weapons>true</weapons>
            <missiles>0</missiles>
            <hasRadar>false</hasRadar>
        </characteristics>
        <parameters>
            <length>9.14</length>
            <width>13.50</width>
            <height>2.85</height>
        </parameters>
        <price>
            <amount>1234567</amount>
            <currency>талер</currency>
        </price>
    </plane>

    <plane>
        <model>Heinkel He 70</model>
        <origin>Германия</origin>
        <characteristics>
            <type>разведчик</type>
            <seats>3</seats>
            <weapons>true</weapons>
            <missiles>0</missiles>
            <hasRadar>true</hasRadar>
        </characteristics>
        <parameters>
            <length>12.00</length>
            <width>14.80</width>
            <height>3.10</height>
        </parameters>
        <price>
            <amount>453334233</amount>
            <currency>талер</currency>
        </price>
    </plane>

    <plane>
        <model>Су-39</model>
        <origin>СССР</origin>
        <characteristics>
            <type>перехватчик</type>
            <seats>1</seats>
            <weapons>true</weapons>
            <missiles>5</missiles>
            <hasRadar>true</hasRadar>
        </characteristics>
        <parameters>
            <length>15.33</length>
            <width>14.36</width>
            <height>5.2</height>
        </parameters>
        <price>
            <amount>785565464</amount>
            <currency>талер</currency>
        </price>
    </plane>

    <plane>
        <model>Douglas A-4 Skyhawk</model>
        <origin>США</origin>
        <characteristics>
            <type>перехватчик</type>
            <seats>1</seats>
            <weapons>true</weapons>
            <missiles>4</missiles>
            <hasRadar>true</hasRadar>
        </characteristics>
        <parameters>
            <length>12.6</length>
            <width>8.4</width>
            <height>4.6</height>
        </parameters>
        <price>
            <amount>76325464</amount>
            <currency>талер</currency>
        </price>
    </plane>
</planes>
